/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gateway_item_protocol_constants.h"

namespace gateway { namespace protocol {

const gateway_item_protocolConstants g_gateway_item_protocol_constants;

gateway_item_protocolConstants::gateway_item_protocolConstants() {
}

}} // namespace

