/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gateway_guild_protocol_CONSTANTS_H
#define gateway_guild_protocol_CONSTANTS_H

#include "gateway_guild_protocol_types.h"

namespace gateway { namespace protocol {

class gateway_guild_protocolConstants {
 public:
  gateway_guild_protocolConstants();

};

extern const gateway_guild_protocolConstants g_gateway_guild_protocol_constants;

}} // namespace

#endif
