/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gateway_social_protocol_CONSTANTS_H
#define gateway_social_protocol_CONSTANTS_H

#include "gateway_social_protocol_types.h"

namespace gateway { namespace protocol {

class gateway_social_protocolConstants {
 public:
  gateway_social_protocolConstants();

};

extern const gateway_social_protocolConstants g_gateway_social_protocol_constants;

}} // namespace

#endif
