/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef session_guild_event_CONSTANTS_H
#define session_guild_event_CONSTANTS_H

#include "session_guild_event_types.h"

namespace session { namespace server { namespace event {

class session_guild_eventConstants {
 public:
  session_guild_eventConstants();

};

extern const session_guild_eventConstants g_session_guild_event_constants;

}}} // namespace

#endif
