/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef session_actor_event_CONSTANTS_H
#define session_actor_event_CONSTANTS_H

#include "session_actor_event_types.h"

namespace session { namespace server { namespace event {

class session_actor_eventConstants {
 public:
  session_actor_eventConstants();

};

extern const session_actor_eventConstants g_session_actor_event_constants;

}}} // namespace

#endif
