/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef session_playing_event_CONSTANTS_H
#define session_playing_event_CONSTANTS_H

#include "session_playing_event_types.h"

namespace session { namespace server { namespace event {

class session_playing_eventConstants {
 public:
  session_playing_eventConstants();

};

extern const session_playing_eventConstants g_session_playing_event_constants;

}}} // namespace

#endif
