/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "actor_constants.h"

namespace entity {

const actorConstants g_actor_constants;

actorConstants::actorConstants() {
}

} // namespace

