/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "equipment_constants.h"

namespace entity {

const equipmentConstants g_equipment_constants;

equipmentConstants::equipmentConstants() {
}

} // namespace

