/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "error_types.h"

#include <algorithm>

namespace entity {

int _kErrorTypeValues[] = {
  ErrorType::MIN,
  ErrorType::ACTOR_BEGIN,
  ErrorType::ACTOR_OFFLINE,
  ErrorType::ACTOR_LEVEL_LOW,
  ErrorType::ACTOR_GOLD_LOW,
  ErrorType::ACTOR_FREEDOM_DOLLAR_LOW,
  ErrorType::ACTOR_RESTRICT_DOLLAR_LOW,
  ErrorType::ITEM_BEGIN,
  ErrorType::PACKET_FULL,
  ErrorType::ITEM_NUMBER,
  ErrorType::SKILL_BEGIN,
  ErrorType::BUFF_BEGIN,
  ErrorType::SCENE_BEGIN,
  ErrorType::SOU_BEGIN,
  ErrorType::TASK_BEGIN,
  ErrorType::TASK_ACCPED_RISK,
  ErrorType::TASK_ACCPED_SAME_TRIP,
  ErrorType::ATTR_BEGIN,
  ErrorType::CHAT_BEGIN,
  ErrorType::MAIL_BEGIN,
  ErrorType::MAIL_ACTOR_INVALID,
  ErrorType::MAIL_ACTOR_BLACKLIST,
  ErrorType::MAIL_CONTEXT_SIZE,
  ErrorType::SOCIAL_BEGIN,
  ErrorType::TEAM_BEGIN,
  ErrorType::TEAM_HAVE_TEAM,
  ErrorType::GUILD_BEGIN,
  ErrorType::MAX
};
const char* _kErrorTypeNames[] = {
  "MIN",
  "ACTOR_BEGIN",
  "ACTOR_OFFLINE",
  "ACTOR_LEVEL_LOW",
  "ACTOR_GOLD_LOW",
  "ACTOR_FREEDOM_DOLLAR_LOW",
  "ACTOR_RESTRICT_DOLLAR_LOW",
  "ITEM_BEGIN",
  "PACKET_FULL",
  "ITEM_NUMBER",
  "SKILL_BEGIN",
  "BUFF_BEGIN",
  "SCENE_BEGIN",
  "SOU_BEGIN",
  "TASK_BEGIN",
  "TASK_ACCPED_RISK",
  "TASK_ACCPED_SAME_TRIP",
  "ATTR_BEGIN",
  "CHAT_BEGIN",
  "MAIL_BEGIN",
  "MAIL_ACTOR_INVALID",
  "MAIL_ACTOR_BLACKLIST",
  "MAIL_CONTEXT_SIZE",
  "SOCIAL_BEGIN",
  "TEAM_BEGIN",
  "TEAM_HAVE_TEAM",
  "GUILD_BEGIN",
  "MAX"
};
const std::map<int, const char*> _ErrorType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(28, _kErrorTypeValues, _kErrorTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
