/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "homeland_constants.h"

namespace entity {

const homelandConstants g_homeland_constants;

homelandConstants::homelandConstants() {
}

} // namespace

