/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef maze_TYPES_H
#define maze_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>



namespace entity {

struct MazeGridType {
  enum type {
    MIN = 0,
    UNEXPLORED = 0,
    NORMAL = 1,
    MAX = 2
  };
};

extern const std::map<int, const char*> _MazeGridType_VALUES_TO_NAMES;

struct MazeDirectionType {
  enum type {
    MIN = 0,
    EAST = 0,
    WEST = 1,
    SOUTH = 2,
    NORTH = 3,
    MAX = 4
  };
};

extern const std::map<int, const char*> _MazeDirectionType_VALUES_TO_NAMES;

} // namespace

#endif
