/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vocation_CONSTANTS_H
#define vocation_CONSTANTS_H

#include "vocation_types.h"

namespace entity {

class vocationConstants {
 public:
  vocationConstants();

};

extern const vocationConstants g_vocation_constants;

} // namespace

#endif
