/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "bar_types.h"

#include <algorithm>

namespace entity {

int _kBarEventTypeValues[] = {
  BarEventType::MIX,
  BarEventType::ACTOR_MOVE,
  BarEventType::ACTOR_DIE,
  BarEventType::ACTOR_HURT,
  BarEventType::ACTOR_SKILL,
  BarEventType::ACTOR_USE_ITEM,
  BarEventType::MAX
};
const char* _kBarEventTypeNames[] = {
  "MIX",
  "ACTOR_MOVE",
  "ACTOR_DIE",
  "ACTOR_HURT",
  "ACTOR_SKILL",
  "ACTOR_USE_ITEM",
  "MAX"
};
const std::map<int, const char*> _BarEventType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(7, _kBarEventTypeValues, _kBarEventTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kBarModuleTypeValues[] = {
  BarModuleType::BAR_INVALID,
  BarModuleType::BAR_TYPE_GATHER,
  BarModuleType::BAR_TYPE_SPIRIT_TRANSFORMED
};
const char* _kBarModuleTypeNames[] = {
  "BAR_INVALID",
  "BAR_TYPE_GATHER",
  "BAR_TYPE_SPIRIT_TRANSFORMED"
};
const std::map<int, const char*> _BarModuleType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kBarModuleTypeValues, _kBarModuleTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
