/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef entity_CONSTANTS_H
#define entity_CONSTANTS_H

#include "entity_types.h"

namespace entity {

class entityConstants {
 public:
  entityConstants();

};

extern const entityConstants g_entity_constants;

} // namespace

#endif
