/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gateway_chat_protocol_constants.h"

namespace gateway { namespace protocol {

const gateway_chat_protocolConstants g_gateway_chat_protocol_constants;

gateway_chat_protocolConstants::gateway_chat_protocolConstants() {
}

}} // namespace

