/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef item_CONSTANTS_H
#define item_CONSTANTS_H

#include "item_types.h"

namespace entity {

class itemConstants {
 public:
  itemConstants();

};

extern const itemConstants g_item_constants;

} // namespace

#endif
