/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kickout_actor_type_TYPES_H
#define kickout_actor_type_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>



namespace global { namespace protocol {

struct KickoutActorType {
  enum type {
    RELOGIN = 0,
    UNKNOWN = 1,
    MAX = 2
  };
};

extern const std::map<int, const char*> _KickoutActorType_VALUES_TO_NAMES;

}} // namespace

#endif
