/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vip_constants.h"

namespace entity {

const vipConstants g_vip_constants;

vipConstants::vipConstants() {
}

} // namespace

