/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vip_CONSTANTS_H
#define vip_CONSTANTS_H

#include "vip_types.h"

namespace entity {

class vipConstants {
 public:
  vipConstants();

};

extern const vipConstants g_vip_constants;

} // namespace

#endif
