#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class MazeGridType:
  MIN = 0
  UNEXPLORED = 0
  NORMAL = 1
  MAX = 2

  _VALUES_TO_NAMES = {
    0: "MIN",
    0: "UNEXPLORED",
    1: "NORMAL",
    2: "MAX",
  }

  _NAMES_TO_VALUES = {
    "MIN": 0,
    "UNEXPLORED": 0,
    "NORMAL": 1,
    "MAX": 2,
  }

class MazeDirectionType:
  MIN = 0
  EAST = 0
  WEST = 1
  SOUTH = 2
  NORTH = 3
  MAX = 4

  _VALUES_TO_NAMES = {
    0: "MIN",
    0: "EAST",
    1: "WEST",
    2: "SOUTH",
    3: "NORTH",
    4: "MAX",
  }

  _NAMES_TO_VALUES = {
    "MIN": 0,
    "EAST": 0,
    "WEST": 1,
    "SOUTH": 2,
    "NORTH": 3,
    "MAX": 4,
  }

