#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class GenderType:
  MIN = 0
  MALE = 1
  FAMAIL = 2
  BOTH = 3
  MAX = 4

  _VALUES_TO_NAMES = {
    0: "MIN",
    1: "MALE",
    2: "FAMAIL",
    3: "BOTH",
    4: "MAX",
  }

  _NAMES_TO_VALUES = {
    "MIN": 0,
    "MALE": 1,
    "FAMAIL": 2,
    "BOTH": 3,
    "MAX": 4,
  }

