/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_soul_request_constants.h"

namespace game { namespace server { namespace request {

const game_soul_requestConstants g_game_soul_request_constants;

game_soul_requestConstants::game_soul_requestConstants() {
}

}}} // namespace

