/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_playing_request_CONSTANTS_H
#define game_playing_request_CONSTANTS_H

#include "game_playing_request_types.h"

namespace game { namespace server { namespace request {

class game_playing_requestConstants {
 public:
  game_playing_requestConstants();

};

extern const game_playing_requestConstants g_game_playing_request_constants;

}}} // namespace

#endif
