/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_effect_request_CONSTANTS_H
#define game_effect_request_CONSTANTS_H

#include "game_effect_request_types.h"

namespace game { namespace server { namespace request {

class game_effect_requestConstants {
 public:
  game_effect_requestConstants();

};

extern const game_effect_requestConstants g_game_effect_request_constants;

}}} // namespace

#endif
