/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_buff_request_constants.h"

namespace game { namespace server { namespace request {

const game_buff_requestConstants g_game_buff_request_constants;

game_buff_requestConstants::game_buff_requestConstants() {
}

}}} // namespace

