/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_actor_protocol_constants.h"

namespace session { namespace protocol {

const game_actor_protocolConstants g_game_actor_protocol_constants;

game_actor_protocolConstants::game_actor_protocolConstants() {
}

}} // namespace

