/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "database_storage_constants.h"

namespace database { namespace protocol {

const database_storageConstants g_database_storage_constants;

database_storageConstants::database_storageConstants() {
}

}} // namespace

