/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_auction_actor_save_constants.h"

namespace database { namespace protocol {

const storage_auction_actor_saveConstants g_storage_auction_actor_save_constants;

storage_auction_actor_saveConstants::storage_auction_actor_saveConstants() {
}

}} // namespace

