/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_mail_affix_constants.h"

namespace database { namespace protocol {

const storage_mail_affixConstants g_storage_mail_affix_constants;

storage_mail_affixConstants::storage_mail_affixConstants() {
  kMailAffixField.push_back("item1");
  kMailAffixField.push_back("item1_num");
  kMailAffixField.push_back("item2");
  kMailAffixField.push_back("item2_num");
  kMailAffixField.push_back("item3");
  kMailAffixField.push_back("item3_num");
  kMailAffixField.push_back("item4");
  kMailAffixField.push_back("item4_num");
  kMailAffixField.push_back("item5");
  kMailAffixField.push_back("item5_num");
  kMailAffixField.push_back("gold");
  kMailAffixField.push_back("freedom_dollars");

}

}} // namespace

