/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef storage_mail_login_CONSTANTS_H
#define storage_mail_login_CONSTANTS_H

#include "storage_mail_login_types.h"

namespace database { namespace protocol {

class storage_mail_loginConstants {
 public:
  storage_mail_loginConstants();

  std::vector<std::string>  kMailLoadField;
};

extern const storage_mail_loginConstants g_storage_mail_login_constants;

}} // namespace

#endif
