/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_gem_login_constants.h"

namespace database { namespace protocol {

const storage_gem_loginConstants g_storage_gem_login_constants;

storage_gem_loginConstants::storage_gem_loginConstants() {
  kGemFieldStr.push_back("location_type");
  kGemFieldStr.push_back("location_index");
  kGemFieldStr.push_back("gem_id");
  kGemFieldStr.push_back("gem_level");
  kGemFieldStr.push_back("gem_exp");
  kGemFieldStr.push_back("locked");

}

}} // namespace

