/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_skill_login_constants.h"

namespace database { namespace protocol {

const storage_skill_loginConstants g_storage_skill_login_constants;

storage_skill_loginConstants::storage_skill_loginConstants() {
  kSkillFieldStr.push_back("skill_id");
  kSkillFieldStr.push_back("skill_current_level");

}

}} // namespace

