#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class CampType:
  TYPE_NONE = 1
  TYPE_NPC_FIELD = 2
  TYPE_MOSTER_FIELD = 3
  TYPE_ACTOR_A_ARENA = 4
  TYPE_ACTOR_B_ARENA = 5
  TYPE_ACTOR_A_PVP = 6
  TYPE_NPC_A_PVP = 7
  TYPE_ACTOR_B_PVP = 8
  TYPE_NPC_B_PVP = 9
  TYPE_EXTENTION = 20

  _VALUES_TO_NAMES = {
    1: "TYPE_NONE",
    2: "TYPE_NPC_FIELD",
    3: "TYPE_MOSTER_FIELD",
    4: "TYPE_ACTOR_A_ARENA",
    5: "TYPE_ACTOR_B_ARENA",
    6: "TYPE_ACTOR_A_PVP",
    7: "TYPE_NPC_A_PVP",
    8: "TYPE_ACTOR_B_PVP",
    9: "TYPE_NPC_B_PVP",
    20: "TYPE_EXTENTION",
  }

  _NAMES_TO_VALUES = {
    "TYPE_NONE": 1,
    "TYPE_NPC_FIELD": 2,
    "TYPE_MOSTER_FIELD": 3,
    "TYPE_ACTOR_A_ARENA": 4,
    "TYPE_ACTOR_B_ARENA": 5,
    "TYPE_ACTOR_A_PVP": 6,
    "TYPE_NPC_A_PVP": 7,
    "TYPE_ACTOR_B_PVP": 8,
    "TYPE_NPC_B_PVP": 9,
    "TYPE_EXTENTION": 20,
  }

class CampRelationType:
  MIN = 0
  HOSTLITY = 1
  FRIENDLY = 2
  NEUTRAL = 3
  NONE = 4
  MAX = 5

  _VALUES_TO_NAMES = {
    0: "MIN",
    1: "HOSTLITY",
    2: "FRIENDLY",
    3: "NEUTRAL",
    4: "NONE",
    5: "MAX",
  }

  _NAMES_TO_VALUES = {
    "MIN": 0,
    "HOSTLITY": 1,
    "FRIENDLY": 2,
    "NEUTRAL": 3,
    "NONE": 4,
    "MAX": 5,
  }

