TARGET= build/libbuzzprotocol
SRCS = \
src/protocol/achieve_constants.cpp \
src/protocol/achieve_types.cpp \
src/protocol/actor_constants.cpp \
src/protocol/actor_types.cpp \
src/protocol/auction_constants.cpp \
src/protocol/auction_types.cpp \
src/protocol/bar_constants.cpp \
src/protocol/bar_types.cpp \
src/protocol/buff_constants.cpp \
src/protocol/buff_types.cpp \
src/protocol/camp_constants.cpp \
src/protocol/camp_types.cpp \
src/protocol/chat_constants.cpp \
src/protocol/chat_types.cpp \
src/protocol/constants_constants.cpp \
src/protocol/constants_types.cpp \
src/protocol/contacts_constants.cpp \
src/protocol/contacts_types.cpp \
src/protocol/cooling_constants.cpp \
src/protocol/cooling_types.cpp \
src/protocol/direction_constants.cpp \
src/protocol/direction_types.cpp \
src/protocol/entity_constants.cpp \
src/protocol/entity_types.cpp \
src/protocol/equipment_constants.cpp \
src/protocol/equipment_types.cpp \
src/protocol/error_constants.cpp \
src/protocol/error_types.cpp \
src/protocol/fight_score_constants.cpp \
src/protocol/fight_score_types.cpp \
src/protocol/functionality_constants.cpp \
src/protocol/functionality_types.cpp \
src/protocol/gateway_attr_protocol_constants.cpp \
src/protocol/gateway_attr_protocol_types.cpp \
src/protocol/gateway_auction_protocol_constants.cpp \
src/protocol/gateway_auction_protocol_types.cpp \
src/protocol/gateway_bar_protocol_constants.cpp \
src/protocol/gateway_bar_protocol_types.cpp \
src/protocol/gateway_buff_protocol_constants.cpp \
src/protocol/gateway_buff_protocol_types.cpp \
src/protocol/gateway_chat_protocol_constants.cpp \
src/protocol/gateway_chat_protocol_types.cpp \
src/protocol/gateway_cooling_protocol_constants.cpp \
src/protocol/gateway_cooling_protocol_types.cpp \
src/protocol/gateway_entity_protocol_constants.cpp \
src/protocol/gateway_entity_protocol_types.cpp \
src/protocol/gateway_error_protocol_constants.cpp \
src/protocol/gateway_error_protocol_types.cpp \
src/protocol/gateway_gm_protocol_constants.cpp \
src/protocol/gateway_gm_protocol_types.cpp \
src/protocol/gateway_guild_protocol_constants.cpp \
src/protocol/gateway_guild_protocol_types.cpp \
src/protocol/gateway_inform_protocol_constants.cpp \
src/protocol/gateway_inform_protocol_types.cpp \
src/protocol/gateway_item_protocol_constants.cpp \
src/protocol/gateway_item_protocol_types.cpp \
src/protocol/gateway_mail_protocol_constants.cpp \
src/protocol/gateway_mail_protocol_types.cpp \
src/protocol/gateway_mall_protocol_constants.cpp \
src/protocol/gateway_mall_protocol_types.cpp \
src/protocol/gateway_playing_protocol_constants.cpp \
src/protocol/gateway_playing_protocol_types.cpp \
src/protocol/gateway_protocol_constants.cpp \
src/protocol/gateway_protocol_types.cpp \
src/protocol/gateway_scene_protocol_constants.cpp \
src/protocol/gateway_scene_protocol_types.cpp \
src/protocol/gateway_shop_protocol_constants.cpp \
src/protocol/gateway_shop_protocol_types.cpp \
src/protocol/gateway_skill_protocol_constants.cpp \
src/protocol/gateway_skill_protocol_types.cpp \
src/protocol/gateway_social_protocol_constants.cpp \
src/protocol/gateway_social_protocol_types.cpp \
src/protocol/gateway_soul_protocol_constants.cpp \
src/protocol/gateway_soul_protocol_types.cpp \
src/protocol/gateway_task_protocol_constants.cpp \
src/protocol/gateway_task_protocol_types.cpp \
src/protocol/gateway_team_protocol_constants.cpp \
src/protocol/gateway_team_protocol_types.cpp \
src/protocol/gateway_transport_protocol_constants.cpp \
src/protocol/gateway_transport_protocol_types.cpp \
src/protocol/gateway_welfare_protocol_constants.cpp \
src/protocol/gateway_welfare_protocol_types.cpp \
src/protocol/gem_constants.cpp \
src/protocol/gem_types.cpp \
src/protocol/gender_constants.cpp \
src/protocol/gender_types.cpp \
src/protocol/guild_constants.cpp \
src/protocol/guild_types.cpp \
src/protocol/homeland_constants.cpp \
src/protocol/homeland_types.cpp \
src/protocol/inform_constants.cpp \
src/protocol/inform_types.cpp \
src/protocol/item_constants.cpp \
src/protocol/item_types.cpp \
src/protocol/kickout_actor_type_constants.cpp \
src/protocol/kickout_actor_type_types.cpp \
src/protocol/login_protocol_constants.cpp \
src/protocol/login_protocol_types.cpp \
src/protocol/mail_constants.cpp \
src/protocol/mail_system_constants.cpp \
src/protocol/mail_system_types.cpp \
src/protocol/mail_types.cpp \
src/protocol/mall_constants.cpp \
src/protocol/mall_types.cpp \
src/protocol/maze_constants.cpp \
src/protocol/maze_types.cpp \
src/protocol/npc_constants.cpp \
src/protocol/npc_types.cpp \
src/protocol/playing_constants.cpp \
src/protocol/playing_types.cpp \
src/protocol/resource_constants.cpp \
src/protocol/resource_types.cpp \
src/protocol/role_constants.cpp \
src/protocol/role_types.cpp \
src/protocol/scene_item_constants.cpp \
src/protocol/scene_item_types.cpp \
src/protocol/server_type_constants.cpp \
src/protocol/server_type_types.cpp \
src/protocol/skill_constants.cpp \
src/protocol/skill_types.cpp \
src/protocol/soul_constants.cpp \
src/protocol/soul_types.cpp \
src/protocol/spirit_constants.cpp \
src/protocol/spirit_types.cpp \
src/protocol/task_constants.cpp \
src/protocol/task_types.cpp \
src/protocol/vip_constants.cpp \
src/protocol/vip_types.cpp \
src/protocol/vocation_constants.cpp \
src/protocol/vocation_types.cpp \
src/protocol/welfare_constants.cpp \
src/protocol/welfare_types.cpp \

CPP_FLAG = -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H
LINK_TYPE = static
INCLUDE = -Isrc
BUILD_DIR = build

include mak/main.mak

