/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_constants.h"

namespace test { namespace chat { namespace protocol {

const protocolConstants g_protocol_constants;

protocolConstants::protocolConstants() {
}

}}} // namespace

