/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_playing_event_CONSTANTS_H
#define game_playing_event_CONSTANTS_H

#include "game_playing_event_types.h"

namespace game { namespace server { namespace event {

class game_playing_eventConstants {
 public:
  game_playing_eventConstants();

};

extern const game_playing_eventConstants g_game_playing_event_constants;

}}} // namespace

#endif
