/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_buff_event_constants.h"

namespace game { namespace server { namespace event {

const game_buff_eventConstants g_game_buff_event_constants;

game_buff_eventConstants::game_buff_eventConstants() {
}

}}} // namespace

