/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_social_event_CONSTANTS_H
#define game_social_event_CONSTANTS_H

#include "game_social_event_types.h"

namespace game { namespace server { namespace event {

class game_social_eventConstants {
 public:
  game_social_eventConstants();

};

extern const game_social_eventConstants g_game_social_event_constants;

}}} // namespace

#endif
