/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_task_event_constants.h"

namespace game { namespace server { namespace event {

const game_task_eventConstants g_game_task_event_constants;

game_task_eventConstants::game_task_eventConstants() {
}

}}} // namespace

