/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "session_request_constants.h"

namespace session { namespace server { namespace request {

const session_requestConstants g_session_request_constants;

session_requestConstants::session_requestConstants() {
}

}}} // namespace

