/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef session_playing_request_CONSTANTS_H
#define session_playing_request_CONSTANTS_H

#include "session_playing_request_types.h"

namespace session { namespace server { namespace request {

class session_playing_requestConstants {
 public:
  session_playing_requestConstants();

};

extern const session_playing_requestConstants g_session_playing_request_constants;

}}} // namespace

#endif
