/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "session_mail_request_constants.h"

namespace session { namespace server { namespace request {

const session_mail_requestConstants g_session_mail_request_constants;

session_mail_requestConstants::session_mail_requestConstants() {
}

}}} // namespace

