/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "session_guild_request_constants.h"

namespace session { namespace server { namespace request {

const session_guild_requestConstants g_session_guild_request_constants;

session_guild_requestConstants::session_guild_requestConstants() {
}

}}} // namespace

