#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class EventAttrSpiritFeed:
  """
  Attributes:
   - actor_id_
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'actor_id_', None, None, ), # 1
  )

  def __init__(self, actor_id_=None,):
    self.actor_id_ = actor_id_

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.actor_id_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('EventAttrSpiritFeed')
    if self.actor_id_ is not None:
      oprot.writeFieldBegin('actor_id_', TType.I32, 1)
      oprot.writeI32(self.actor_id_)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.actor_id_ is None:
      raise TProtocol.TProtocolException(message='Required field actor_id_ is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class EventAttrConstellationUpgrade:
  """
  Attributes:
   - actor_id_
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'actor_id_', None, None, ), # 1
  )

  def __init__(self, actor_id_=None,):
    self.actor_id_ = actor_id_

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.actor_id_ = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('EventAttrConstellationUpgrade')
    if self.actor_id_ is not None:
      oprot.writeFieldBegin('actor_id_', TType.I64, 1)
      oprot.writeI64(self.actor_id_)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.actor_id_ is None:
      raise TProtocol.TProtocolException(message='Required field actor_id_ is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class EventAttrSpiritUpgrade:
  """
  Attributes:
   - actor_id_
   - old_level_
   - new_level_
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'actor_id_', None, None, ), # 1
    (2, TType.I32, 'old_level_', None, None, ), # 2
    (3, TType.I32, 'new_level_', None, None, ), # 3
  )

  def __init__(self, actor_id_=None, old_level_=None, new_level_=None,):
    self.actor_id_ = actor_id_
    self.old_level_ = old_level_
    self.new_level_ = new_level_

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.actor_id_ = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.old_level_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.new_level_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('EventAttrSpiritUpgrade')
    if self.actor_id_ is not None:
      oprot.writeFieldBegin('actor_id_', TType.I64, 1)
      oprot.writeI64(self.actor_id_)
      oprot.writeFieldEnd()
    if self.old_level_ is not None:
      oprot.writeFieldBegin('old_level_', TType.I32, 2)
      oprot.writeI32(self.old_level_)
      oprot.writeFieldEnd()
    if self.new_level_ is not None:
      oprot.writeFieldBegin('new_level_', TType.I32, 3)
      oprot.writeI32(self.new_level_)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.actor_id_ is None:
      raise TProtocol.TProtocolException(message='Required field actor_id_ is unset!')
    if self.old_level_ is None:
      raise TProtocol.TProtocolException(message='Required field old_level_ is unset!')
    if self.new_level_ is None:
      raise TProtocol.TProtocolException(message='Required field new_level_ is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class EventAttrSwordUpgrade:
  """
  Attributes:
   - actor_id_
   - old_step_
   - new_step_
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'actor_id_', None, None, ), # 1
    (2, TType.I32, 'old_step_', None, None, ), # 2
    (3, TType.I32, 'new_step_', None, None, ), # 3
  )

  def __init__(self, actor_id_=None, old_step_=None, new_step_=None,):
    self.actor_id_ = actor_id_
    self.old_step_ = old_step_
    self.new_step_ = new_step_

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.actor_id_ = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.old_step_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.new_step_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('EventAttrSwordUpgrade')
    if self.actor_id_ is not None:
      oprot.writeFieldBegin('actor_id_', TType.I64, 1)
      oprot.writeI64(self.actor_id_)
      oprot.writeFieldEnd()
    if self.old_step_ is not None:
      oprot.writeFieldBegin('old_step_', TType.I32, 2)
      oprot.writeI32(self.old_step_)
      oprot.writeFieldEnd()
    if self.new_step_ is not None:
      oprot.writeFieldBegin('new_step_', TType.I32, 3)
      oprot.writeI32(self.new_step_)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.actor_id_ is None:
      raise TProtocol.TProtocolException(message='Required field actor_id_ is unset!')
    if self.old_step_ is None:
      raise TProtocol.TProtocolException(message='Required field old_step_ is unset!')
    if self.new_step_ is None:
      raise TProtocol.TProtocolException(message='Required field new_step_ is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class EventAttrNobleUpgrade:
  """
  Attributes:
   - actor_id_
   - old_level_
   - new_level_
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'actor_id_', None, None, ), # 1
    (2, TType.I32, 'old_level_', None, None, ), # 2
    (3, TType.I32, 'new_level_', None, None, ), # 3
  )

  def __init__(self, actor_id_=None, old_level_=None, new_level_=None,):
    self.actor_id_ = actor_id_
    self.old_level_ = old_level_
    self.new_level_ = new_level_

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.actor_id_ = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.old_level_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.new_level_ = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('EventAttrNobleUpgrade')
    if self.actor_id_ is not None:
      oprot.writeFieldBegin('actor_id_', TType.I64, 1)
      oprot.writeI64(self.actor_id_)
      oprot.writeFieldEnd()
    if self.old_level_ is not None:
      oprot.writeFieldBegin('old_level_', TType.I32, 2)
      oprot.writeI32(self.old_level_)
      oprot.writeFieldEnd()
    if self.new_level_ is not None:
      oprot.writeFieldBegin('new_level_', TType.I32, 3)
      oprot.writeI32(self.new_level_)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.actor_id_ is None:
      raise TProtocol.TProtocolException(message='Required field actor_id_ is unset!')
    if self.old_level_ is None:
      raise TProtocol.TProtocolException(message='Required field old_level_ is unset!')
    if self.new_level_ is None:
      raise TProtocol.TProtocolException(message='Required field new_level_ is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
