#!/bin/bash
#find ./ -iname \*.h -exec grep --color -n -H "$1" \{\} \;
#find ./ -iname \*.cc -exec grep --color -n -H "$1" \{\} \;
#find ./ -iname \*.cpp -exec grep --color -n -H "$1" \{\} \;
#find ./ -iname \*.c -exec grep --color -n -H "$1" \{\} \;

find ./ \( -name \*.cc -o -name \*.h -o -name \*.cpp \) -exec grep --color -n -H "$1" \{\} \;
